2023-01-25 09:09:19 I Canar Print           "Connet 20563 successfully!!!"
2023-01-25 09:09:19 I Canar Get_alltests    "Get project name:Canary id:20563 all testplans"
2023-01-25 09:09:21 I Canar Get_alltests    "{9508431: {'id': 9508431, 'name': 'ESW Test Plan', 'archived': False, 'index': '9508431:ESW Test Plan'}, 9246564: {'id': 9246564, 'name': 'HW Test Plan', 'archived': False, 'index': '9246564:HW Test Plan'}, 8686340: {'id': 8686340, 'name': 'Product Verification Test Plan', 'archived': False, 'index': '8686340:Product Verification Test Plan'}}"
2023-01-25 09:09:21 I Canar Get_alltests    "Get project name:Canary id:20563 all testplans successful!!!"
2023-01-25 09:10:46 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82881/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047F1510>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2023-01-25 09:10:46 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82882/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047F1150>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2023-01-25 09:10:50 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82887/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047F1330>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2023-01-25 09:11:14 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82902/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03E164D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2023-01-25 09:11:49 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82882/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04162930>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2023-01-25 09:11:56 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82908/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04162070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2023-01-25 09:12:17 E Canar Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/testplans/9508431/testgroups/82902/testcases?startAt=0&maxResults=50 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03D62D70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
